# The project list is in .mvn/maven.config because invoker.goals splits on commas.
invoker.goals=${project.groupId}:${project.artifactId}:${project.version}:set -DnewVersion=2.0 -DgenerateBackupPoms=false
