<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>localhost</groupId>
  <artifactId>it-set-issue-1339</artifactId>
  <version>9.0</version>
  <packaging>pom</packaging>
  <modules>
    <module>parent</module>
    <module>bom</module>
    <module>tests</module>
    <module>unrelated</module>
  </modules>
</project>
