version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  exclude-paths:
    - "versions-common/src/test/resources/**"
    - "versions-enforcer/src/it/**"
    - "versions-maven-plugin/src/it/**"
    - "versions-maven-plugin/src/test/resources/**"
  schedule:
    interval: daily
  ignore:
    # plexus-xml 4.x depends on the Maven 4 XML API
    - dependency-name: "org.codehaus.plexus:plexus-xml"
      versions: [">= 4.0.0"]
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
